### ISSUE TITLE
dyld: Library not loaded: /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS

### ISSUE THREAD

**Issue by 0x5e** [DiegoMagdaleno/EzChRoot#5]
Hi, I was trying to add /usr/bin/codesign, /usr/bin/security into coreApplication lists, the create command was success, but I can't start them with missing framework error:

```
sh-3.2$ codesign
dyld: dyld cache load error: shared cache file open() failed
dyld: Library not loaded: /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
  Referenced from: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
  Reason: image not found
Abort trap: 6
```

I copy the whole /System/Library/Framerowks, /System/Library/PrivateFramerowks, /usr/lib, and the next error is:
```
sh-3.2$ security create-keychain -p 123456 test.keychain
security: SecKeychainCreate test.keychain: A Module Directory Service error has occurred.
```

I have few questions:
1. Is it okay to add some binary into coreApplications which is essential for iOS develop(codesign, security, and more)? or can we manually provide the list as an argument to you?
2. The second error seem that I need to launch some services, do you have any ideas?

My final goal is to create a seprate iOS build enviroment, making xcode, code signing, cocoapods, jenkins works, hope your project can help, thanks :)

**Comment by DiegoMagdaleno** [comment]
Sorry for not replying yet, I didn't get a notification.

And yeah it should be possible to do a development environment.

What version of macOS are you using?

**Comment by DiegoMagdaleno** [comment]
Also when you say "Some launch services" it makes me thing the issue here might be the lack of launchd in the chroot.

Also, this program is going to be rewritten eventually as macOS Big Sur changed a lot of stuff, I am more than glad to help you with this, as it is also part of my goal.

I don't know about the possibilities of running full xcode, but it would be a pretty interesting idea, I don't know if it is possible to run Graphical apps inside a chroot in macOS but it would be very interesting.

About cocapods and more it would be possible since thats dependant on Ruby, if you could provide me your macOS version would be very useful!.

And also, I love to assist on this :). I can't test yet, due to the changes in Big Sur, but I am sure this goal is somewhat possible.

Glad you use my software.

**Comment by 0x5e** [comment]
Hi @DiegoMagdaleno I'm using macOS 10.15.5. I've tried to launch opendirectory service and some keychain or user things in chroot (I can't remember), things got worse, the host machine got weird behavior until reboot.
Comparing with docker/linux, macOS is lack of namespace to separate process, choot may not enough to do much things :(
My another thought is: create a mininum macOS base image and run in virtualbox, which is a little bit lightweight than full macOS.

**Comment by DiegoMagdaleno** [comment]
I see, seems like the issue here is more like the way Darwin handles processes :/
